# fly.toml app configuration file generated for manhattan-arcades on 2024-09-17T19:11:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'manhattan-arcades'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80  # For HTTP traffic
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443  # For HTTPS traffic
  
[[services.http_checks]]
  interval = 10000  # 10 seconds
  timeout = 5000    # Increase timeout to 5 seconds
  grace_period = "2m"  # Give more time for the app to start
  method = "GET"
  path = "/health"
  protocol = "http"
  port = 5000


[checks]
  [checks.http]
    port = 5000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2

[mounts]
  source = "pg_data"
  destination = "/data"