# fly.toml app configuration file generated for manhattan-arcades on 2024-09-16T23:22:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'manhattan-arcades'
primary_region = 'ewr'

[build]
  command = "node server.js"


[http_service]
  internal_port = 5000  # This is the port your backend is running on
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.http]
    type = "http"  # Add this line to specify the check type
    path = "/"
    method = "get"
    port = 5000  # Ensure this matches your backend's port
    interval = "15s"
    timeout = "10s"
